# Generated by Django 5.0.2 on 2024-02-18 07:19

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default=None, upload_to='')),
                ('Product_Name', models.CharField(max_length=50)),
                ('Sub_description', tinymce.models.HTMLField(max_length=1000)),
                ('Catagory', models.CharField(choices=[('Camera', 'Camera'), ('Audio', 'Audio'), ('Filter', 'Filter'), ('Lenses', 'Lenses'), ('Gopro Series', 'Gopro Series'), ('Lights', 'Lights'), ('Macbook', 'Macbook'), ('Plasma', 'Plasma')], max_length=15)),
                ('Description', tinymce.models.HTMLField(max_length=1000)),
                ('Youtube_Link', models.URLField()),
                ('Best_seller', models.BooleanField(default=False)),
                ('Top_rate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Products')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Add_Products.show_products')),
            ],
        ),
    ]
