# Generated by Django 5.0.2 on 2024-02-18 09:41

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Products', '0002_demomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show_products',
            name='Description',
            field=tinymce.models.HTMLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='show_products',
            name='Sub_description',
            field=tinymce.models.HTMLField(max_length=2000),
        ),
    ]
