# Generated by Django 5.0.2 on 2024-02-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Products', '0004_cart_cartitem_cart_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Choose_Banner_For', models.CharField(choices=[('Home Page - Lookbook', 'Home Page - Lookbook'), ('Home Page - Over.S18', 'Home Page - Over.S18'), ('Home Page - Style.S16', 'Home Page - Style.S16'), ('Video Production - Lookbook', 'Video Production - Lookbook'), ('Video Production - Over.S18', 'Video Production - Over.S18'), ('Video Production - Style.S16', 'Video Production - Style.S16'), ('About', 'About'), ('Frequently Questions', 'Frequently Questions'), ('Contact', 'Contact')], max_length=40)),
                ('Image', models.ImageField(upload_to='Banners')),
                ('Title', models.CharField(max_length=30)),
                ('Sub_title', models.CharField(max_length=50)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='show_products',
            name='Sale',
            field=models.BooleanField(default=False),
        ),
    ]
