# Generated by Django 5.0.2 on 2024-02-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Products', '0005_banner_show_products_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show_products',
            name='Catagory',
            field=models.CharField(choices=[('Camera', 'Camera'), ('Lenses & Grid', 'Lenses & Grid'), ('Rings & Grips', 'Rings & Grips'), ('Audio', 'Audio'), ('Lights', 'Lights'), ('Filter', 'Filter'), ('Studio & Accessories', 'Studio & Accessories')], max_length=30),
        ),
    ]
