# Generated by Django 5.0.2 on 2024-02-25 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Products', '0006_alter_show_products_catagory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemoModel',
        ),
    ]
