# Generated by Django 5.0.2 on 2024-03-08 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Products', '0009_frequently_questions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Frequently_Questions',
            new_name='Frequently_Question',
        ),
    ]
