# Generated by Django 5.0.2 on 2024-03-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Products', '0011_alter_show_products_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show_products',
            name='Catagory',
            field=models.CharField(choices=[('Camera', 'Camera'), ('Lenses', 'Lenses'), ('Rings & Grips', 'Rings & Grips'), ('Audio', 'Audio'), ('Lights', 'Lights'), ('Filter', 'Filter')], max_length=30),
        ),
    ]
