# Generated by Django 5.0.2 on 2024-03-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Products', '0012_alter_show_products_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='Choose_Banner_For',
            field=models.CharField(choices=[('Home Page - Shutter', 'Home Page - Shutter'), ('Home Page - Experience', 'Home Page - Experience'), ('Home Page - Vision', 'Home Page - Vision'), ('Video Production - Shutter', 'Video Production - Shutter'), ('Video Production - Experience', 'Video Production - Experience'), ('Video Production - Vision', 'Video Production - Vision'), ('About', 'About'), ('Frequently Questions', 'Frequently Questions'), ('Contact', 'Contact')], max_length=40),
        ),
    ]
