# Generated by Django 5.0.2 on 2024-04-01 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Products', '0014_alter_banner_choose_banner_for'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Frequently_Question',
        ),
    ]
