# Generated by Django 5.0.2 on 2024-04-01 19:41

import Add_Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Products', '0016_alter_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='Image',
            field=models.ImageField(help_text='Maximum file size allowed is 1Mb', upload_to='Banners', validators=[Add_Products.models.validate_image]),
        ),
    ]
