# Generated by Django 5.0.2 on 2024-04-01 19:45

import Add_Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add_Products', '0018_alter_show_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_images',
            name='Image',
            field=models.ImageField(help_text='Maximum file size allowed is 1Mb', upload_to='Products', validators=[Add_Products.models.validate_image]),
        ),
    ]
